# Generated by Django 3.0.2 on 2020-02-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraping',
            name='title',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
